### PR TITLE
Add pages: singInUp, error, newsAndAdd, edit

### PR DESCRIPTION
**Pull request by AlexeSemenenko**

### CODE REVIEW

**Comment by MaksimViarenich** [comment]
Not in technical requirements
Снимок экрана 2020-02-24 в 23 34 04

**Comment by MaksimViarenich** [comment]
Incorrect footer
Снимок экрана 2020-02-24 в 23 38 22
Снимок экрана 2020-02-24 в 23 13 13

**Comment by MaksimViarenich** [comment]
Error is a page, not icon with tooltip
Снимок экрана 2020-02-24 в 23 40 09

**Comment by MaksimViarenich** [comment]
Can't find logic for delete
Снимок экрана 2020-02-24 в 20 43 37

**Comment by MaksimViarenich** [comment]
Can't find Log Out and More buttons

**Comment by MaksimViarenich** [comment]
According to mockups it's not clear how to work with filters.

**Comment by MaksimViarenich** [comment]
Add/Edit is a page. You should add/edit twitt in another page and after clicking by Add/Update button return to the Main page
Снимок экрана 2020-02-24 в 23 44 02

**Comment by AlexeSemenenko** [comment]
> Add/Edit is a page. You should add/edit twitt in another page and after clicking by Add/Update button return to the Main page
> Снимок экрана 2020-02-24 в 23 44 02

Got it. Please check the new version with fixed mistakes.

**Review by MaksimViarenich — APPROVED** [review]

**Pull request merged**
